language: node_js
sudo: required
node_js:
  - 6
# travis call prepare 
# create the minify version
before_install:
  #for installing the dev version of terminus-client
  - |
    if [[  $TRAVIS_BRANCH == 'dev' ]]; then
      cd ../
      git clone https://github.com/terminusdb/terminus-client.git
      cd  terminus-client
      git checkout dev
      npm install 
      cd ../terminus-dashboard
      npm run installClient:local
    fi
  - |
    if [[  $TRAVIS_BRANCH == 'master' && $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*  ]]; then
      echo "__INCREMENT_VERSION_NUMBER__"
      export PACKAGE_VERSION=$(npm version patch)
    fi

# after_script: "npm run build:all"
# after_success:

branches:
  only:
    - dev
    - master

before_deploy:
  - |
    if [[ ! $TRAVIS_VAR ]]; then
      npm run build
      echo "___TRAVIS_VAR____"
      export TRAVIS_VAR="1.$TRAVIS_BUILD_NUMBER"

      git commit --amend -m "[skip travis] version changed $PACKAGE_VERSION"
      git push https://${GITHUB_TOKEN}@github.com/$TRAVIS_REPO_SLUG HEAD:$TRAVIS_BRANCH
      git tag -f -a "$PACKAGE_VERSION" -m "new version $PACKAGE_VERSION"
      export LAST_HASH=$(git ls-remote https://github.com/$TRAVIS_REPO_SLUG refs/heads/$TRAVIS_BRANCH | awk '{ print $1}')
    fi

#LAST_HASH=$(git ls-remote  https://github.com/terminusdb/terminus-dashboard.git master | awk '{ print $1}')
#https://blog.travis-ci.com/2018-04-11-how_to_publish_node_js_packages_with_travis_ci_and_packagecloud/
deploy:
  - provider: releases
    target_commitish : $LAST_HASH
    keep_history: true
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    overwrite: true
    file : package-lock.json
    on:
      branch: master 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
  - provider: script
    skip_cleanup: true
    keep_history: true
    script: bash public_pages.sh
    on:
      branch: master 
      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*
#  - provider: npm
#    registry: "https://registry.npmjs.org/"
#    skip_cleanup: true
#    access: public
#    email: "francesca@datachemist.com"
#    api_key: $NPM_TOKEN
#    keep_history: true
#    auth_method: "authToken"
#    on:
#      branch : master
#      condition: $TRAVIS_COMMIT_MESSAGE == *"[run deploy]"*


